### ISSUE TITLE
Feature Request:  support day 2 actions

### ISSUE THREAD

**Issue by arthurdm** [appsody/appsody-operator#126]
This is a feature request to support day 2 actions, such as enabling trace, produce a JVM dump, etc.

The initial thought is that we could have a new CRD that the Operator watches for, such as `AppsodyAction`.  

So the user could then apply a new CR that triggered an action against a deployment.  

Here's an early strawman to illustrate (we need to design this properly):

```
apiVersion: appsody.dev/v1beta1
kind: AppsodyAction
metadata:
  name: action1
spec:
  refDeployment: <ref to deployment name>
  <action name>:
      <action configuration>
```

The status, via `oc get appsodyaction <metadata.name>` can specify when the action has been completed, and provide more details about it to the user (via `-o wide`).

kAppNav can then display available actions through its UI, and trigger those by under the covers creating and applying the corresponding CRs.
