### ISSUE TITLE
Service not getting created intermittently when switching from Knative to non-Knative

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#138]
### What did you do?

Changed `createKnativeService` from `true` to `false` in the following CR:
```yaml
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: demo-day
  labels:
    name: navid
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: navidsh/demo-day:latest
  stack: nodejs-express
  service:
    type: NodePort
    port: 3000
    annotations:
      prometheus.io/scrape: 'true'
  expose: true
  createKnativeService: false
```

### What did you expect to see?

Knative service and other resources created by Knative get deleted and regular k8s resources such as service, pod and etc. get created.

### What did you see instead?

Service object was not created by the operator. Other resources such as deployment, pod and route were created. This happens intermittently.

### Environment

* Appsody CLI version: N/A

* Appsody Stack: N/A

* Kubernetes version information: N/A

### Additional context

**Workaround:** Changing any field in the CR that causes the operator to go through `reconcile` loop such as changing `expose` field, results in a service to be created back.
