### ISSUE TITLE
Support ServiceMonitor for deployed applications

### ISSUE THREAD

**Issue by arthurdm** [appsody/appsody-operator#46]
We need a key under service (perhaps `service.enableMonitoring`) where under the covers our operator creates the ServiceMonitor that the Prometheus Operator is watching.

**Comment by navidsh** [comment]
With the following resource definitions, Prometheus operator was able to scrape metrics from Liberty through HTTPS with basic user registry enabled. Liberty used self-signed certificates.

`ServiceMonitor`:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: myapp-monitor
  name: myapp-monitor
  namespace: appsody-app
spec:
  endpoints:
    - basicAuth:
        password:
          key: password
          name: appsody-app
        username:
          key: username
          name: appsody-app
      interval: 5s
      path: /metrics
      scheme: https
      targetPort: 9443
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - appsody-app
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics
```

`AppsodyApplication`:
```yaml
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: metrics
  namespace: appsody-app
spec:
  applicationImage: 'navidsh/metrics:latest'
  expose: true
  livenessProbe:
    failureThreshold: 30
    httpGet:
      path: /health/live
      port: 9443
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 5
  pullPolicy: Always
  readinessProbe:
    failureThreshold: 30
    httpGet:
      path: /health/ready
      port: 9443
      scheme: HTTPS
    initialDelaySeconds: 30
    periodSeconds: 5
  resourceConstraints:
    requests:
      memory: 512Mi
  service:
    annotations:
      prometheus.io/scrape: 'true'
    port: 9443
    type: NodePort
  stack: java-microprofile
```

`Prometheus`:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: appsody-monitoring
  labels:
    prometheus: prometheus
spec:
  enableAdminAPI: false
  resources:
    requests:
      memory: 400Mi
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      prometheus: monitoring
  serviceMonitorSelector:
    matchExpressions:
      - key: k8s-app
        operator: Exists
```

`appsody-app` namespace was labelled with `prometheus: monitoring`
