### ISSUE TITLE
Copy labels set on CR to resources created by the operator

### ISSUE THREAD

**Issue by navidsh** [appsody/appsody-operator#84]
Users should be able to set custom labels on CRs and the operator should copy those labels into all resources created by the operator. This way users can set custom labels on all resources. e.g.

```yaml
apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: my-appsody-app
  labels:
    environment: production
    team: frontend
spec:
  stack: java-microprofile
  applicationImage: quay.io/my-repo/my-app:1.0
```

Users should be able to override the default labels added by the Appsody operator when users provide the same label key.
